branch-defaults:
  default:
    environment: Udacity-env
environment-defaults:
  Udacity-env:
    branch: null
    repository: null
global:
  application_name: udacity
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
deploy:
  artifact: ./www/Archive.zip
