version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  build-frontend:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build frontnend
          command: npm run build:frontend

  deploy-frontend:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Deploy frontnend
          command: npm run deploy:frontend


workflows:
  sample:
    jobs:
      - build-frontend
      - build-backend
      - deploy-frontend
      - deploy-backend
