version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
#      - node/install
      - aws-cli/setup
      - eb/setup
#      - browser-tools/install-browser-tools
#      - run:
#          name: Install Frontend
#          command: |
#            npm run install:frontend
#      - run:
#          name: Install Backend
#          command: |
#            npm run install:backend
#      - run:
#          name: Build Frontend
#          command: |
#            npm run build:frontend
#      - run:
#          name: Test Frontend
#          command: |
#            npm run test:frontend
#      - run:
#          name: Build Backend
#          command: |
#            npm run build:backend
#      - run:
#          name: Deployment
#          command: |
#            npm run deploy:frontend
#      - run:
#          name: Deployment
#          command: |
#            npm run deploy:backend
      - eb/deploy:
          context: aws-creds
          environment-name: Udacity-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>




workflows:
  workflow:
    jobs:
      - build
