version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - run:
          name: Install Frontend
          command: |
            npm run install:frontend
      - run:
          name: Install Backend
          command: |
            npm run install:backend
      - run:
          name: Build Frontend
          command: |
            npm run build:frontend
      - run:
          name: Build Backend
          command: |
            npm run build:backend
      - run:
          name: Deploy
          command: |
            npm run deploy




workflows:
  workflow:
    jobs:
      - build
